### ISSUE TITLE
Doesn't work with @angular packages

### ISSUE THREAD

**Issue by unsafecode** [eladnava/tldrlegal#2] opened 2017-02-17 13:48 UTC
## Issue
I have an @angular@2.4.5 project, and I get the following error:

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\XXX/node_modules/@angular/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getPackage (C:\Users\XXX\AppData\Roaming\nvm\v6.9.1\node_modules\tldrlegal\node_modules\legally\lib\legally.js:14:13)
    at folders.reduce (C:\Users\XXX\AppData\Roaming\nvm\v6.9.1\node_modules\tldrlegal\node_modules\legally\lib\legally.js:21:6)
    at Array.reduce (native)
    at module.exports.root (C:\Users\XXX\AppData\Roaming\nvm\v6.9.1\node_modules\tldrlegal\node_modules\legally\lib\legally.js:19:40)
    at Object.<anonymous> (C:\Users\XXX\AppData\Roaming\nvm\v6.9.1\node_modules\tldrlegal\index.js:17:16)
    at Module._compile (module.js:570:32)
```

## System info
win10, node@6.9.1

**Comment by eladnava** [comment] 2017-02-17 22:12
Thanks for reporting!

This is a duplicate of #1, an upstream bug in `legally`. Once fixed, I'll update the version if needed.

**Closed as completed by eladnava** 2017-02-17 22:12 UTC

**Comment by eladnava** [comment] 2017-02-23 19:06
This has been fixed, see [this](https://github.com/eladnava/tldrlegal/issues/1#issuecomment-282018270).
